using backend.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace backend.Persistence.Configurations;

public class LetterHarakatItemConfiguration : IEntityTypeConfiguration<LetterHarakatItem>
{
    private static Guid G(int n) => new($"00000000-0000-0000-0000-{n:D12}");

    public void Configure(EntityTypeBuilder<LetterHarakatItem> builder)
    {
        builder.HasKey(i => i.Id);
        builder.Property(i => i.Sound      ).HasMaxLength(20);
        builder.Property(i => i.ExampleWord).HasMaxLength(100);

        builder.HasOne(i => i.Letter)
               .WithMany(l => l.HarakatItems)
               .HasForeignKey(i => i.LetterId)
               .OnDelete(DeleteBehavior.Cascade);

        builder.HasOne(i => i.Category)
               .WithMany(c => c.Items)
               .HasForeignKey(i => i.CategoryId)
               .OnDelete(DeleteBehavior.Cascade);

        builder.HasIndex(i => new { i.LetterId, i.CategoryId }).IsUnique();
        builder.ToTable("LetterHarakatItems");

        builder.HasData(
            new LetterHarakatItem { Id =   1, LetterId = G(1), CategoryId = 1, Sound = "Aa", ExampleWord = "أَحَد" },
            new LetterHarakatItem { Id =   2, LetterId = G(1), CategoryId = 2, Sound = "Ii", ExampleWord = "إِيمَان" },
            new LetterHarakatItem { Id =   3, LetterId = G(1), CategoryId = 3, Sound = "Uu", ExampleWord = "أُمَّة" },
            new LetterHarakatItem { Id =   4, LetterId = G(1), CategoryId = 4, Sound = "", ExampleWord = "الْحَمْد" },
            new LetterHarakatItem { Id =   5, LetterId = G(1), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id =   6, LetterId = G(1), CategoryId = 6, Sound = "Aan", ExampleWord = "إِمَامًا" },
            new LetterHarakatItem { Id =   7, LetterId = G(1), CategoryId = 7, Sound = "Iin", ExampleWord = "إِمَامٍ" },
            new LetterHarakatItem { Id =   8, LetterId = G(1), CategoryId = 8, Sound = "Uun", ExampleWord = "إِمَامٌ" },
            new LetterHarakatItem { Id =   9, LetterId = G(2), CategoryId = 1, Sound = "Ba", ExampleWord = "بَيْت" },
            new LetterHarakatItem { Id =  10, LetterId = G(2), CategoryId = 2, Sound = "Bi", ExampleWord = "بِسْمِ اللَّه" },
            new LetterHarakatItem { Id =  11, LetterId = G(2), CategoryId = 3, Sound = "Bu", ExampleWord = "بُرُوج" },
            new LetterHarakatItem { Id =  12, LetterId = G(2), CategoryId = 4, Sound = "", ExampleWord = "عَبْد" },
            new LetterHarakatItem { Id =  13, LetterId = G(2), CategoryId = 5, Sound = "", ExampleWord = "رَبَّنَا" },
            new LetterHarakatItem { Id =  14, LetterId = G(2), CategoryId = 6, Sound = "Ban", ExampleWord = "كِتَابًا" },
            new LetterHarakatItem { Id =  15, LetterId = G(2), CategoryId = 7, Sound = "Bin", ExampleWord = "كِتَابٍ" },
            new LetterHarakatItem { Id =  16, LetterId = G(2), CategoryId = 8, Sound = "Bun", ExampleWord = "كِتَابٌ" },
            new LetterHarakatItem { Id =  17, LetterId = G(3), CategoryId = 1, Sound = "Ta", ExampleWord = "تَوْبَة" },
            new LetterHarakatItem { Id =  18, LetterId = G(3), CategoryId = 2, Sound = "Ti", ExampleWord = "تِلْكَ" },
            new LetterHarakatItem { Id =  19, LetterId = G(3), CategoryId = 3, Sound = "Tu", ExampleWord = "تُوبُوا" },
            new LetterHarakatItem { Id =  20, LetterId = G(3), CategoryId = 4, Sound = "", ExampleWord = "أَنْتَ" },
            new LetterHarakatItem { Id =  21, LetterId = G(3), CategoryId = 5, Sound = "", ExampleWord = "اتَّقُوا" },
            new LetterHarakatItem { Id =  22, LetterId = G(3), CategoryId = 6, Sound = "Tan", ExampleWord = "رَحْمَةً" },
            new LetterHarakatItem { Id =  23, LetterId = G(3), CategoryId = 7, Sound = "Tin", ExampleWord = "رَحْمَةٍ" },
            new LetterHarakatItem { Id =  24, LetterId = G(3), CategoryId = 8, Sound = "Tun", ExampleWord = "رَحْمَةٌ" },
            new LetterHarakatItem { Id =  25, LetterId = G(4), CategoryId = 1, Sound = "Tha", ExampleWord = "ثَوْب" },
            new LetterHarakatItem { Id =  26, LetterId = G(4), CategoryId = 2, Sound = "Thi", ExampleWord = "ثِقَال" },
            new LetterHarakatItem { Id =  27, LetterId = G(4), CategoryId = 3, Sound = "Thu", ExampleWord = "ثُمَّ" },
            new LetterHarakatItem { Id =  28, LetterId = G(4), CategoryId = 4, Sound = "", ExampleWord = "حَيْثُ" },
            new LetterHarakatItem { Id =  29, LetterId = G(4), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id =  30, LetterId = G(4), CategoryId = 6, Sound = "Than", ExampleWord = "حَدِيثًا" },
            new LetterHarakatItem { Id =  31, LetterId = G(4), CategoryId = 7, Sound = "Thin", ExampleWord = "حَدِيثٍ" },
            new LetterHarakatItem { Id =  32, LetterId = G(4), CategoryId = 8, Sound = "Thun", ExampleWord = "حَدِيثٌ" },
            new LetterHarakatItem { Id =  33, LetterId = G(5), CategoryId = 1, Sound = "Ja", ExampleWord = "جَنَّة" },
            new LetterHarakatItem { Id =  34, LetterId = G(5), CategoryId = 2, Sound = "Ji", ExampleWord = "جِهَاد" },
            new LetterHarakatItem { Id =  35, LetterId = G(5), CategoryId = 3, Sound = "Ju", ExampleWord = "جُزْء" },
            new LetterHarakatItem { Id =  36, LetterId = G(5), CategoryId = 4, Sound = "", ExampleWord = "أَجْر" },
            new LetterHarakatItem { Id =  37, LetterId = G(5), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id =  38, LetterId = G(5), CategoryId = 6, Sound = "Jan", ExampleWord = "أَجْرًا" },
            new LetterHarakatItem { Id =  39, LetterId = G(5), CategoryId = 7, Sound = "Jin", ExampleWord = "أَجْرٍ" },
            new LetterHarakatItem { Id =  40, LetterId = G(5), CategoryId = 8, Sound = "Jun", ExampleWord = "أَجْرٌ" },
            new LetterHarakatItem { Id =  41, LetterId = G(6), CategoryId = 1, Sound = "Ha", ExampleWord = "حَمْد" },
            new LetterHarakatItem { Id =  42, LetterId = G(6), CategoryId = 2, Sound = "Hi", ExampleWord = "حِكْمَة" },
            new LetterHarakatItem { Id =  43, LetterId = G(6), CategoryId = 3, Sound = "Hu", ExampleWord = "حُكْم" },
            new LetterHarakatItem { Id =  44, LetterId = G(6), CategoryId = 4, Sound = "", ExampleWord = "رَحْمَة" },
            new LetterHarakatItem { Id =  45, LetterId = G(6), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id =  46, LetterId = G(6), CategoryId = 6, Sound = "Han", ExampleWord = "فَرَحًا" },
            new LetterHarakatItem { Id =  47, LetterId = G(6), CategoryId = 7, Sound = "Hin", ExampleWord = "فَرَحٍ" },
            new LetterHarakatItem { Id =  48, LetterId = G(6), CategoryId = 8, Sound = "Hun", ExampleWord = "فَرَحٌ" },
            new LetterHarakatItem { Id =  49, LetterId = G(7), CategoryId = 1, Sound = "Kha", ExampleWord = "خَلَق" },
            new LetterHarakatItem { Id =  50, LetterId = G(7), CategoryId = 2, Sound = "Khi", ExampleWord = "خِلَاف" },
            new LetterHarakatItem { Id =  51, LetterId = G(7), CategoryId = 3, Sound = "Khu", ExampleWord = "خُلُق" },
            new LetterHarakatItem { Id =  52, LetterId = G(7), CategoryId = 4, Sound = "", ExampleWord = "أَخْبَار" },
            new LetterHarakatItem { Id =  53, LetterId = G(7), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id =  54, LetterId = G(7), CategoryId = 6, Sound = "Khan", ExampleWord = "خَيْرًا" },
            new LetterHarakatItem { Id =  55, LetterId = G(7), CategoryId = 7, Sound = "Khin", ExampleWord = "خَيْرٍ" },
            new LetterHarakatItem { Id =  56, LetterId = G(7), CategoryId = 8, Sound = "Khun", ExampleWord = "خَيْرٌ" },
            new LetterHarakatItem { Id =  57, LetterId = G(8), CategoryId = 1, Sound = "Da", ExampleWord = "دَعَا" },
            new LetterHarakatItem { Id =  58, LetterId = G(8), CategoryId = 2, Sound = "Di", ExampleWord = "دِين" },
            new LetterHarakatItem { Id =  59, LetterId = G(8), CategoryId = 3, Sound = "Du", ExampleWord = "دُعَاء" },
            new LetterHarakatItem { Id =  60, LetterId = G(8), CategoryId = 4, Sound = "", ExampleWord = "هُدْى" },
            new LetterHarakatItem { Id =  61, LetterId = G(8), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id =  62, LetterId = G(8), CategoryId = 6, Sound = "Dan", ExampleWord = "مَسْجِدًا" },
            new LetterHarakatItem { Id =  63, LetterId = G(8), CategoryId = 7, Sound = "Din", ExampleWord = "مَسْجِدٍ" },
            new LetterHarakatItem { Id =  64, LetterId = G(8), CategoryId = 8, Sound = "Dun", ExampleWord = "مَسْجِدٌ" },
            new LetterHarakatItem { Id =  65, LetterId = G(9), CategoryId = 1, Sound = "Dha", ExampleWord = "ذَلِكَ" },
            new LetterHarakatItem { Id =  66, LetterId = G(9), CategoryId = 2, Sound = "Dhi", ExampleWord = "ذِكْر" },
            new LetterHarakatItem { Id =  67, LetterId = G(9), CategoryId = 3, Sound = "Dhu", ExampleWord = "ذُنُوب" },
            new LetterHarakatItem { Id =  68, LetterId = G(9), CategoryId = 4, Sound = "", ExampleWord = "إِذْ" },
            new LetterHarakatItem { Id =  69, LetterId = G(9), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id =  70, LetterId = G(9), CategoryId = 6, Sound = "Dhan", ExampleWord = "عَذَابًا" },
            new LetterHarakatItem { Id =  71, LetterId = G(9), CategoryId = 7, Sound = "Dhin", ExampleWord = "عَذَابٍ" },
            new LetterHarakatItem { Id =  72, LetterId = G(9), CategoryId = 8, Sound = "Dhun", ExampleWord = "عَذَابٌ" },
            new LetterHarakatItem { Id =  73, LetterId = G(10), CategoryId = 1, Sound = "Ra", ExampleWord = "رَحْمَة" },
            new LetterHarakatItem { Id =  74, LetterId = G(10), CategoryId = 2, Sound = "Ri", ExampleWord = "رِزْق" },
            new LetterHarakatItem { Id =  75, LetterId = G(10), CategoryId = 3, Sound = "Ru", ExampleWord = "رُسُل" },
            new LetterHarakatItem { Id =  76, LetterId = G(10), CategoryId = 4, Sound = "", ExampleWord = "أَرْض" },
            new LetterHarakatItem { Id =  77, LetterId = G(10), CategoryId = 5, Sound = "", ExampleWord = "رَبَّنَا" },
            new LetterHarakatItem { Id =  78, LetterId = G(10), CategoryId = 6, Sound = "Ran", ExampleWord = "نُورًا" },
            new LetterHarakatItem { Id =  79, LetterId = G(10), CategoryId = 7, Sound = "Rin", ExampleWord = "نُورٍ" },
            new LetterHarakatItem { Id =  80, LetterId = G(10), CategoryId = 8, Sound = "Run", ExampleWord = "نُورٌ" },
            new LetterHarakatItem { Id =  81, LetterId = G(11), CategoryId = 1, Sound = "Za", ExampleWord = "زَيْت" },
            new LetterHarakatItem { Id =  82, LetterId = G(11), CategoryId = 2, Sound = "Zi", ExampleWord = "زِينَة" },
            new LetterHarakatItem { Id =  83, LetterId = G(11), CategoryId = 3, Sound = "Zu", ExampleWord = "زُهُور" },
            new LetterHarakatItem { Id =  84, LetterId = G(11), CategoryId = 4, Sound = "", ExampleWord = "أَزْوَاج" },
            new LetterHarakatItem { Id =  85, LetterId = G(11), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id =  86, LetterId = G(11), CategoryId = 6, Sound = "Zan", ExampleWord = "رِزْقًا" },
            new LetterHarakatItem { Id =  87, LetterId = G(11), CategoryId = 7, Sound = "Zin", ExampleWord = "رِزْقٍ" },
            new LetterHarakatItem { Id =  88, LetterId = G(11), CategoryId = 8, Sound = "Zun", ExampleWord = "رِزْقٌ" },
            new LetterHarakatItem { Id =  89, LetterId = G(12), CategoryId = 1, Sound = "Sa", ExampleWord = "سَلَام" },
            new LetterHarakatItem { Id =  90, LetterId = G(12), CategoryId = 2, Sound = "Si", ExampleWord = "سِرَاج" },
            new LetterHarakatItem { Id =  91, LetterId = G(12), CategoryId = 3, Sound = "Su", ExampleWord = "سُورَة" },
            new LetterHarakatItem { Id =  92, LetterId = G(12), CategoryId = 4, Sound = "", ExampleWord = "مَسْجِد" },
            new LetterHarakatItem { Id =  93, LetterId = G(12), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id =  94, LetterId = G(12), CategoryId = 6, Sound = "San", ExampleWord = "سَلَامًا" },
            new LetterHarakatItem { Id =  95, LetterId = G(12), CategoryId = 7, Sound = "Sin", ExampleWord = "سَلَامٍ" },
            new LetterHarakatItem { Id =  96, LetterId = G(12), CategoryId = 8, Sound = "Sun", ExampleWord = "سَلَامٌ" },
            new LetterHarakatItem { Id =  97, LetterId = G(13), CategoryId = 1, Sound = "Sha", ExampleWord = "شَمْس" },
            new LetterHarakatItem { Id =  98, LetterId = G(13), CategoryId = 2, Sound = "Shi", ExampleWord = "شِفَاء" },
            new LetterHarakatItem { Id =  99, LetterId = G(13), CategoryId = 3, Sound = "Shu", ExampleWord = "شُكْر" },
            new LetterHarakatItem { Id = 100, LetterId = G(13), CategoryId = 4, Sound = "", ExampleWord = "عَشْر" },
            new LetterHarakatItem { Id = 101, LetterId = G(13), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id = 102, LetterId = G(13), CategoryId = 6, Sound = "Shan", ExampleWord = "عَرْشًا" },
            new LetterHarakatItem { Id = 103, LetterId = G(13), CategoryId = 7, Sound = "Shin", ExampleWord = "عَرْشٍ" },
            new LetterHarakatItem { Id = 104, LetterId = G(13), CategoryId = 8, Sound = "Shun", ExampleWord = "عَرْشٌ" },
            new LetterHarakatItem { Id = 105, LetterId = G(14), CategoryId = 1, Sound = "Sa", ExampleWord = "صَلَاة" },
            new LetterHarakatItem { Id = 106, LetterId = G(14), CategoryId = 2, Sound = "Si", ExampleWord = "صِرَاط" },
            new LetterHarakatItem { Id = 107, LetterId = G(14), CategoryId = 3, Sound = "Su", ExampleWord = "صُدُور" },
            new LetterHarakatItem { Id = 108, LetterId = G(14), CategoryId = 4, Sound = "", ExampleWord = "أَصْحَاب" },
            new LetterHarakatItem { Id = 109, LetterId = G(14), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id = 110, LetterId = G(14), CategoryId = 6, Sound = "San", ExampleWord = "صَبْرًا" },
            new LetterHarakatItem { Id = 111, LetterId = G(14), CategoryId = 7, Sound = "Sin", ExampleWord = "صَبْرٍ" },
            new LetterHarakatItem { Id = 112, LetterId = G(14), CategoryId = 8, Sound = "Sun", ExampleWord = "صَبْرٌ" },
            new LetterHarakatItem { Id = 113, LetterId = G(15), CategoryId = 1, Sound = "Da", ExampleWord = "ضَلَال" },
            new LetterHarakatItem { Id = 114, LetterId = G(15), CategoryId = 2, Sound = "Di", ExampleWord = "ضِيَاء" },
            new LetterHarakatItem { Id = 115, LetterId = G(15), CategoryId = 3, Sound = "Du", ExampleWord = "ضُعَفَاء" },
            new LetterHarakatItem { Id = 116, LetterId = G(15), CategoryId = 4, Sound = "", ExampleWord = "أَرْض" },
            new LetterHarakatItem { Id = 117, LetterId = G(15), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id = 118, LetterId = G(15), CategoryId = 6, Sound = "Dan", ExampleWord = "فَضْلًا" },
            new LetterHarakatItem { Id = 119, LetterId = G(15), CategoryId = 7, Sound = "Din", ExampleWord = "فَضْلٍ" },
            new LetterHarakatItem { Id = 120, LetterId = G(15), CategoryId = 8, Sound = "Dun", ExampleWord = "فَضْلٌ" },
            new LetterHarakatItem { Id = 121, LetterId = G(16), CategoryId = 1, Sound = "Ta", ExampleWord = "طَرِيق" },
            new LetterHarakatItem { Id = 122, LetterId = G(16), CategoryId = 2, Sound = "Ti", ExampleWord = "طِفْل" },
            new LetterHarakatItem { Id = 123, LetterId = G(16), CategoryId = 3, Sound = "Tu", ExampleWord = "طُهُور" },
            new LetterHarakatItem { Id = 124, LetterId = G(16), CategoryId = 4, Sound = "", ExampleWord = "قِطْعَة" },
            new LetterHarakatItem { Id = 125, LetterId = G(16), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id = 126, LetterId = G(16), CategoryId = 6, Sound = "Tan", ExampleWord = "خَطًّا" },
            new LetterHarakatItem { Id = 127, LetterId = G(16), CategoryId = 7, Sound = "Tin", ExampleWord = "خَطٍّ" },
            new LetterHarakatItem { Id = 128, LetterId = G(16), CategoryId = 8, Sound = "Tun", ExampleWord = "خَطٌّ" },
            new LetterHarakatItem { Id = 129, LetterId = G(17), CategoryId = 1, Sound = "Dha", ExampleWord = "ظَلَمَ" },
            new LetterHarakatItem { Id = 130, LetterId = G(17), CategoryId = 2, Sound = "Dhi", ExampleWord = "ظِلّ" },
            new LetterHarakatItem { Id = 131, LetterId = G(17), CategoryId = 3, Sound = "Dhu", ExampleWord = "ظُلْمَة" },
            new LetterHarakatItem { Id = 132, LetterId = G(17), CategoryId = 4, Sound = "", ExampleWord = "حِفْظ" },
            new LetterHarakatItem { Id = 133, LetterId = G(17), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id = 134, LetterId = G(17), CategoryId = 6, Sound = "Dhan", ExampleWord = "ظُلْمًا" },
            new LetterHarakatItem { Id = 135, LetterId = G(17), CategoryId = 7, Sound = "Dhin", ExampleWord = "ظُلْمٍ" },
            new LetterHarakatItem { Id = 136, LetterId = G(17), CategoryId = 8, Sound = "Dhun", ExampleWord = "ظُلْمٌ" },
            new LetterHarakatItem { Id = 137, LetterId = G(18), CategoryId = 1, Sound = "'Aa", ExampleWord = "عَمَل" },
            new LetterHarakatItem { Id = 138, LetterId = G(18), CategoryId = 2, Sound = "'Ii", ExampleWord = "عِلْم" },
            new LetterHarakatItem { Id = 139, LetterId = G(18), CategoryId = 3, Sound = "'Uu", ExampleWord = "عُلَمَاء" },
            new LetterHarakatItem { Id = 140, LetterId = G(18), CategoryId = 4, Sound = "", ExampleWord = "يَعْلَم" },
            new LetterHarakatItem { Id = 141, LetterId = G(18), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id = 142, LetterId = G(18), CategoryId = 6, Sound = "'Aan", ExampleWord = "عِلْمًا" },
            new LetterHarakatItem { Id = 143, LetterId = G(18), CategoryId = 7, Sound = "'Iin", ExampleWord = "عِلْمٍ" },
            new LetterHarakatItem { Id = 144, LetterId = G(18), CategoryId = 8, Sound = "'Uun", ExampleWord = "عِلْمٌ" },
            new LetterHarakatItem { Id = 145, LetterId = G(19), CategoryId = 1, Sound = "Gha", ExampleWord = "غَفَر" },
            new LetterHarakatItem { Id = 146, LetterId = G(19), CategoryId = 2, Sound = "Ghi", ExampleWord = "غِطَاء" },
            new LetterHarakatItem { Id = 147, LetterId = G(19), CategoryId = 3, Sound = "Ghu", ExampleWord = "غُرُور" },
            new LetterHarakatItem { Id = 148, LetterId = G(19), CategoryId = 4, Sound = "", ExampleWord = "يَغْفِر" },
            new LetterHarakatItem { Id = 149, LetterId = G(19), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id = 150, LetterId = G(19), CategoryId = 6, Sound = "Ghan", ExampleWord = "غَيْبًا" },
            new LetterHarakatItem { Id = 151, LetterId = G(19), CategoryId = 7, Sound = "Ghin", ExampleWord = "غَيْبٍ" },
            new LetterHarakatItem { Id = 152, LetterId = G(19), CategoryId = 8, Sound = "Ghun", ExampleWord = "غَيْبٌ" },
            new LetterHarakatItem { Id = 153, LetterId = G(20), CategoryId = 1, Sound = "Fa", ExampleWord = "فَجْر" },
            new LetterHarakatItem { Id = 154, LetterId = G(20), CategoryId = 2, Sound = "Fi", ExampleWord = "فِطْرَة" },
            new LetterHarakatItem { Id = 155, LetterId = G(20), CategoryId = 3, Sound = "Fu", ExampleWord = "فُؤَاد" },
            new LetterHarakatItem { Id = 156, LetterId = G(20), CategoryId = 4, Sound = "", ExampleWord = "أَفْلَح" },
            new LetterHarakatItem { Id = 157, LetterId = G(20), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id = 158, LetterId = G(20), CategoryId = 6, Sound = "Fan", ExampleWord = "فَجْرًا" },
            new LetterHarakatItem { Id = 159, LetterId = G(20), CategoryId = 7, Sound = "Fin", ExampleWord = "فَجْرٍ" },
            new LetterHarakatItem { Id = 160, LetterId = G(20), CategoryId = 8, Sound = "Fun", ExampleWord = "فَجْرٌ" },
            new LetterHarakatItem { Id = 161, LetterId = G(21), CategoryId = 1, Sound = "Qa", ExampleWord = "قَلْب" },
            new LetterHarakatItem { Id = 162, LetterId = G(21), CategoryId = 2, Sound = "Qi", ExampleWord = "قِيَامَة" },
            new LetterHarakatItem { Id = 163, LetterId = G(21), CategoryId = 3, Sound = "Qu", ExampleWord = "قُرْآن" },
            new LetterHarakatItem { Id = 164, LetterId = G(21), CategoryId = 4, Sound = "", ExampleWord = "حَقّ" },
            new LetterHarakatItem { Id = 165, LetterId = G(21), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id = 166, LetterId = G(21), CategoryId = 6, Sound = "Qan", ExampleWord = "حَقًّا" },
            new LetterHarakatItem { Id = 167, LetterId = G(21), CategoryId = 7, Sound = "Qin", ExampleWord = "حَقٍّ" },
            new LetterHarakatItem { Id = 168, LetterId = G(21), CategoryId = 8, Sound = "Qun", ExampleWord = "حَقٌّ" },
            new LetterHarakatItem { Id = 169, LetterId = G(22), CategoryId = 1, Sound = "Ka", ExampleWord = "كَرِيم" },
            new LetterHarakatItem { Id = 170, LetterId = G(22), CategoryId = 2, Sound = "Ki", ExampleWord = "كِتَاب" },
            new LetterHarakatItem { Id = 171, LetterId = G(22), CategoryId = 3, Sound = "Ku", ExampleWord = "كُفْر" },
            new LetterHarakatItem { Id = 172, LetterId = G(22), CategoryId = 4, Sound = "", ExampleWord = "يَكْتُب" },
            new LetterHarakatItem { Id = 173, LetterId = G(22), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id = 174, LetterId = G(22), CategoryId = 6, Sound = "Kan", ExampleWord = "مَلِكًا" },
            new LetterHarakatItem { Id = 175, LetterId = G(22), CategoryId = 7, Sound = "Kin", ExampleWord = "مَلِكٍ" },
            new LetterHarakatItem { Id = 176, LetterId = G(22), CategoryId = 8, Sound = "Kun", ExampleWord = "مَلِكٌ" },
            new LetterHarakatItem { Id = 177, LetterId = G(23), CategoryId = 1, Sound = "La", ExampleWord = "لَيْل" },
            new LetterHarakatItem { Id = 178, LetterId = G(23), CategoryId = 2, Sound = "Li", ExampleWord = "لِسَان" },
            new LetterHarakatItem { Id = 179, LetterId = G(23), CategoryId = 3, Sound = "Lu", ExampleWord = "لُغَة" },
            new LetterHarakatItem { Id = 180, LetterId = G(23), CategoryId = 4, Sound = "", ExampleWord = "عِلْم" },
            new LetterHarakatItem { Id = 181, LetterId = G(23), CategoryId = 5, Sound = "", ExampleWord = "اللَّه" },
            new LetterHarakatItem { Id = 182, LetterId = G(23), CategoryId = 6, Sound = "Lan", ExampleWord = "لَيْلًا" },
            new LetterHarakatItem { Id = 183, LetterId = G(23), CategoryId = 7, Sound = "Lin", ExampleWord = "لَيْلٍ" },
            new LetterHarakatItem { Id = 184, LetterId = G(23), CategoryId = 8, Sound = "Lun", ExampleWord = "لَيْلٌ" },
            new LetterHarakatItem { Id = 185, LetterId = G(24), CategoryId = 1, Sound = "Ma", ExampleWord = "مَاء" },
            new LetterHarakatItem { Id = 186, LetterId = G(24), CategoryId = 2, Sound = "Mi", ExampleWord = "مِيزَان" },
            new LetterHarakatItem { Id = 187, LetterId = G(24), CategoryId = 3, Sound = "Mu", ExampleWord = "مُؤْمِن" },
            new LetterHarakatItem { Id = 188, LetterId = G(24), CategoryId = 4, Sound = "", ExampleWord = "يَعْلَمُون" },
            new LetterHarakatItem { Id = 189, LetterId = G(24), CategoryId = 5, Sound = "", ExampleWord = "إِنَّمَا" },
            new LetterHarakatItem { Id = 190, LetterId = G(24), CategoryId = 6, Sound = "Man", ExampleWord = "عِلْمًا" },
            new LetterHarakatItem { Id = 191, LetterId = G(24), CategoryId = 7, Sound = "Min", ExampleWord = "عِلْمٍ" },
            new LetterHarakatItem { Id = 192, LetterId = G(24), CategoryId = 8, Sound = "Mun", ExampleWord = "عَالِمٌ" },
            new LetterHarakatItem { Id = 193, LetterId = G(25), CategoryId = 1, Sound = "Na", ExampleWord = "نَعِيم" },
            new LetterHarakatItem { Id = 194, LetterId = G(25), CategoryId = 2, Sound = "Ni", ExampleWord = "نِعْمَة" },
            new LetterHarakatItem { Id = 195, LetterId = G(25), CategoryId = 3, Sound = "Nu", ExampleWord = "نُور" },
            new LetterHarakatItem { Id = 196, LetterId = G(25), CategoryId = 4, Sound = "", ExampleWord = "إِنْ" },
            new LetterHarakatItem { Id = 197, LetterId = G(25), CategoryId = 5, Sound = "", ExampleWord = "إِنَّ" },
            new LetterHarakatItem { Id = 198, LetterId = G(25), CategoryId = 6, Sound = "Nan", ExampleWord = "نُورًا" },
            new LetterHarakatItem { Id = 199, LetterId = G(25), CategoryId = 7, Sound = "Nin", ExampleWord = "نُورٍ" },
            new LetterHarakatItem { Id = 200, LetterId = G(25), CategoryId = 8, Sound = "Nun", ExampleWord = "نُورٌ" },
            new LetterHarakatItem { Id = 201, LetterId = G(26), CategoryId = 1, Sound = "Wa", ExampleWord = "وَلَد" },
            new LetterHarakatItem { Id = 202, LetterId = G(26), CategoryId = 2, Sound = "Wi", ExampleWord = "وِلَادَة" },
            new LetterHarakatItem { Id = 203, LetterId = G(26), CategoryId = 3, Sound = "Wu", ExampleWord = "وُجُوه" },
            new LetterHarakatItem { Id = 204, LetterId = G(26), CategoryId = 4, Sound = "", ExampleWord = "يَوْم" },
            new LetterHarakatItem { Id = 205, LetterId = G(26), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id = 206, LetterId = G(26), CategoryId = 6, Sound = "Wan", ExampleWord = "يَوْمًا" },
            new LetterHarakatItem { Id = 207, LetterId = G(26), CategoryId = 7, Sound = "Win", ExampleWord = "يَوْمٍ" },
            new LetterHarakatItem { Id = 208, LetterId = G(26), CategoryId = 8, Sound = "Wun", ExampleWord = "يَوْمٌ" },
            new LetterHarakatItem { Id = 209, LetterId = G(27), CategoryId = 1, Sound = "Ha", ExampleWord = "هَدَى" },
            new LetterHarakatItem { Id = 210, LetterId = G(27), CategoryId = 2, Sound = "Hi", ExampleWord = "هِدَايَة" },
            new LetterHarakatItem { Id = 211, LetterId = G(27), CategoryId = 3, Sound = "Hu", ExampleWord = "هُدَى" },
            new LetterHarakatItem { Id = 212, LetterId = G(27), CategoryId = 4, Sound = "", ExampleWord = "يَهْدِي" },
            new LetterHarakatItem { Id = 213, LetterId = G(27), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id = 214, LetterId = G(27), CategoryId = 6, Sound = "Han", ExampleWord = "هَدْيًا" },
            new LetterHarakatItem { Id = 215, LetterId = G(27), CategoryId = 7, Sound = "Hin", ExampleWord = "هَدْيٍ" },
            new LetterHarakatItem { Id = 216, LetterId = G(27), CategoryId = 8, Sound = "Hun", ExampleWord = "هَدْيٌ" },
            new LetterHarakatItem { Id = 217, LetterId = G(28), CategoryId = 1, Sound = "Ya", ExampleWord = "يَوْم" },
            new LetterHarakatItem { Id = 218, LetterId = G(28), CategoryId = 2, Sound = "Yi", ExampleWord = "يَدِيهِ" },
            new LetterHarakatItem { Id = 219, LetterId = G(28), CategoryId = 3, Sound = "Yu", ExampleWord = "يُوسُف" },
            new LetterHarakatItem { Id = 220, LetterId = G(28), CategoryId = 4, Sound = "", ExampleWord = "خَيْر" },
            new LetterHarakatItem { Id = 221, LetterId = G(28), CategoryId = 5, Sound = "", ExampleWord = "" },
            new LetterHarakatItem { Id = 222, LetterId = G(28), CategoryId = 6, Sound = "Yan", ExampleWord = "شَيْئًا" },
            new LetterHarakatItem { Id = 223, LetterId = G(28), CategoryId = 7, Sound = "Yin", ExampleWord = "شَيْءٍ" },
            new LetterHarakatItem { Id = 224, LetterId = G(28), CategoryId = 8, Sound = "Yun", ExampleWord = "شَيْءٌ" }
        );
    }
}
