using backend.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace backend.Persistence.Configurations;

public class SurahConfiguration : IEntityTypeConfiguration<Surah>
{
    public void Configure(EntityTypeBuilder<Surah> builder)
    {
        builder.HasKey(s => s.Id);

        builder.Property(s => s.NameArabic).IsRequired().HasMaxLength(200);
        builder.Property(s => s.NameEnglish).IsRequired().HasMaxLength(200);
        builder.Property(s => s.NameBangla).IsRequired().HasMaxLength(200);

        builder.HasIndex(s => s.SurahNumber).IsUnique();

        builder.ToTable("Surahs");

        builder.HasData(
            new Surah { Id = 1, SurahNumber = 1, NameArabic = "ٱلْفَاتِحَةِ", NameEnglish = "Al-Faatiha", NameBangla = "The Opening", TotalAyahs = 7 },
            new Surah { Id = 2, SurahNumber = 2, NameArabic = "البَقَرَةِ", NameEnglish = "Al-Baqara", NameBangla = "The Cow", TotalAyahs = 286 },
            new Surah { Id = 3, SurahNumber = 3, NameArabic = "آلِ عِمۡرَانَ", NameEnglish = "Aal-i-Imraan", NameBangla = "The Family of Imraan", TotalAyahs = 200 },
            new Surah { Id = 4, SurahNumber = 4, NameArabic = "النِّسَاءِ", NameEnglish = "An-Nisaa", NameBangla = "The Women", TotalAyahs = 176 },
            new Surah { Id = 5, SurahNumber = 5, NameArabic = "المَائـِدَةِ", NameEnglish = "Al-Maaida", NameBangla = "The Table", TotalAyahs = 120 },
            new Surah { Id = 6, SurahNumber = 6, NameArabic = "الأَنۡعَامِ", NameEnglish = "Al-An'aam", NameBangla = "The Cattle", TotalAyahs = 165 },
            new Surah { Id = 7, SurahNumber = 7, NameArabic = "الأَعۡرَافِ", NameEnglish = "Al-A'raaf", NameBangla = "The Heights", TotalAyahs = 206 },
            new Surah { Id = 8, SurahNumber = 8, NameArabic = "الأَنفَالِ", NameEnglish = "Al-Anfaal", NameBangla = "The Spoils of War", TotalAyahs = 75 },
            new Surah { Id = 9, SurahNumber = 9, NameArabic = "التَّوۡبَةِ", NameEnglish = "At-Tawba", NameBangla = "The Repentance", TotalAyahs = 129 },
            new Surah { Id = 10, SurahNumber = 10, NameArabic = "يُونُسَ", NameEnglish = "Yunus", NameBangla = "Jonas", TotalAyahs = 109 },
            new Surah { Id = 11, SurahNumber = 11, NameArabic = "هُودٍ", NameEnglish = "Hud", NameBangla = "Hud", TotalAyahs = 123 },
            new Surah { Id = 12, SurahNumber = 12, NameArabic = "يُوسُفَ", NameEnglish = "Yusuf", NameBangla = "Joseph", TotalAyahs = 111 },
            new Surah { Id = 13, SurahNumber = 13, NameArabic = "الرَّعۡدِ", NameEnglish = "Ar-Ra'd", NameBangla = "The Thunder", TotalAyahs = 43 },
            new Surah { Id = 14, SurahNumber = 14, NameArabic = "إِبۡرَاهِيمَ", NameEnglish = "Ibrahim", NameBangla = "Abraham", TotalAyahs = 52 },
            new Surah { Id = 15, SurahNumber = 15, NameArabic = "الحِجۡرِ", NameEnglish = "Al-Hijr", NameBangla = "The Rock", TotalAyahs = 99 },
            new Surah { Id = 16, SurahNumber = 16, NameArabic = "النَّحۡلِ", NameEnglish = "An-Nahl", NameBangla = "The Bee", TotalAyahs = 128 },
            new Surah { Id = 17, SurahNumber = 17, NameArabic = "الإِسۡرَاءِ", NameEnglish = "Al-Israa", NameBangla = "The Night Journey", TotalAyahs = 111 },
            new Surah { Id = 18, SurahNumber = 18, NameArabic = "الكَهۡفِ", NameEnglish = "Al-Kahf", NameBangla = "The Cave", TotalAyahs = 110 },
            new Surah { Id = 19, SurahNumber = 19, NameArabic = "مَرۡيَمَ", NameEnglish = "Maryam", NameBangla = "Mary", TotalAyahs = 98 },
            new Surah { Id = 20, SurahNumber = 20, NameArabic = "طه", NameEnglish = "Taa-Haa", NameBangla = "Taa-Haa", TotalAyahs = 135 },
            new Surah { Id = 21, SurahNumber = 21, NameArabic = "الأَنبِيَاءِ", NameEnglish = "Al-Anbiyaa", NameBangla = "The Prophets", TotalAyahs = 112 },
            new Surah { Id = 22, SurahNumber = 22, NameArabic = "الحَجِّ", NameEnglish = "Al-Hajj", NameBangla = "The Pilgrimage", TotalAyahs = 78 },
            new Surah { Id = 23, SurahNumber = 23, NameArabic = "المُؤۡمِنُونَ", NameEnglish = "Al-Muminoon", NameBangla = "The Believers", TotalAyahs = 118 },
            new Surah { Id = 24, SurahNumber = 24, NameArabic = "النُّورِ", NameEnglish = "An-Noor", NameBangla = "The Light", TotalAyahs = 64 },
            new Surah { Id = 25, SurahNumber = 25, NameArabic = "الفُرۡقَانِ", NameEnglish = "Al-Furqaan", NameBangla = "The Criterion", TotalAyahs = 77 },
            new Surah { Id = 26, SurahNumber = 26, NameArabic = "الشُّعَرَاءِ", NameEnglish = "Ash-Shu'araa", NameBangla = "The Poets", TotalAyahs = 227 },
            new Surah { Id = 27, SurahNumber = 27, NameArabic = "النَّمۡلِ", NameEnglish = "An-Naml", NameBangla = "The Ant", TotalAyahs = 93 },
            new Surah { Id = 28, SurahNumber = 28, NameArabic = "القَصَصِ", NameEnglish = "Al-Qasas", NameBangla = "The Stories", TotalAyahs = 88 },
            new Surah { Id = 29, SurahNumber = 29, NameArabic = "العَنكَبُوتِ", NameEnglish = "Al-Ankaboot", NameBangla = "The Spider", TotalAyahs = 69 },
            new Surah { Id = 30, SurahNumber = 30, NameArabic = "الرُّومِ", NameEnglish = "Ar-Room", NameBangla = "The Romans", TotalAyahs = 60 },
            new Surah { Id = 31, SurahNumber = 31, NameArabic = "لُقۡمَانَ", NameEnglish = "Luqman", NameBangla = "Luqman", TotalAyahs = 34 },
            new Surah { Id = 32, SurahNumber = 32, NameArabic = "السَّجۡدَةِ", NameEnglish = "As-Sajda", NameBangla = "The Prostration", TotalAyahs = 30 },
            new Surah { Id = 33, SurahNumber = 33, NameArabic = "الأَحۡزَابِ", NameEnglish = "Al-Ahzaab", NameBangla = "The Clans", TotalAyahs = 73 },
            new Surah { Id = 34, SurahNumber = 34, NameArabic = "سَبَإٍ", NameEnglish = "Saba", NameBangla = "Sheba", TotalAyahs = 54 },
            new Surah { Id = 35, SurahNumber = 35, NameArabic = "فَاطِرٍ", NameEnglish = "Faatir", NameBangla = "The Originator", TotalAyahs = 45 },
            new Surah { Id = 36, SurahNumber = 36, NameArabic = "يسٓ", NameEnglish = "Yaseen", NameBangla = "Yaseen", TotalAyahs = 83 },
            new Surah { Id = 37, SurahNumber = 37, NameArabic = "الصَّافَّاتِ", NameEnglish = "As-Saaffaat", NameBangla = "Those drawn up in Ranks", TotalAyahs = 182 },
            new Surah { Id = 38, SurahNumber = 38, NameArabic = "صٓ", NameEnglish = "Saad", NameBangla = "The letter Saad", TotalAyahs = 88 },
            new Surah { Id = 39, SurahNumber = 39, NameArabic = "الزُّمَرِ", NameEnglish = "Az-Zumar", NameBangla = "The Groups", TotalAyahs = 75 },
            new Surah { Id = 40, SurahNumber = 40, NameArabic = "غَافِرٍ", NameEnglish = "Ghafir", NameBangla = "The Forgiver", TotalAyahs = 85 },
            new Surah { Id = 41, SurahNumber = 41, NameArabic = "فُصِّلَتۡ", NameEnglish = "Fussilat", NameBangla = "Explained in detail", TotalAyahs = 54 },
            new Surah { Id = 42, SurahNumber = 42, NameArabic = "الشُّورَىٰ", NameEnglish = "Ash-Shura", NameBangla = "Consultation", TotalAyahs = 53 },
            new Surah { Id = 43, SurahNumber = 43, NameArabic = "الزُّخۡرُفِ", NameEnglish = "Az-Zukhruf", NameBangla = "Ornaments of gold", TotalAyahs = 89 },
            new Surah { Id = 44, SurahNumber = 44, NameArabic = "الدُّخَانِ", NameEnglish = "Ad-Dukhaan", NameBangla = "The Smoke", TotalAyahs = 59 },
            new Surah { Id = 45, SurahNumber = 45, NameArabic = "الجَاثِيَةِ", NameEnglish = "Al-Jaathiya", NameBangla = "Crouching", TotalAyahs = 37 },
            new Surah { Id = 46, SurahNumber = 46, NameArabic = "الأَحۡقَافِ", NameEnglish = "Al-Ahqaf", NameBangla = "The Dunes", TotalAyahs = 35 },
            new Surah { Id = 47, SurahNumber = 47, NameArabic = "مُحَمَّدٍ", NameEnglish = "Muhammad", NameBangla = "Muhammad", TotalAyahs = 38 },
            new Surah { Id = 48, SurahNumber = 48, NameArabic = "الفَتۡحِ", NameEnglish = "Al-Fath", NameBangla = "The Victory", TotalAyahs = 29 },
            new Surah { Id = 49, SurahNumber = 49, NameArabic = "الحُجُرَاتِ", NameEnglish = "Al-Hujuraat", NameBangla = "The Inner Apartments", TotalAyahs = 18 },
            new Surah { Id = 50, SurahNumber = 50, NameArabic = "قٓ", NameEnglish = "Qaaf", NameBangla = "The letter Qaaf", TotalAyahs = 45 },
            new Surah { Id = 51, SurahNumber = 51, NameArabic = "الذَّارِيَاتِ", NameEnglish = "Adh-Dhaariyat", NameBangla = "The Winnowing Winds", TotalAyahs = 60 },
            new Surah { Id = 52, SurahNumber = 52, NameArabic = "الطُّورِ", NameEnglish = "At-Tur", NameBangla = "The Mount", TotalAyahs = 49 },
            new Surah { Id = 53, SurahNumber = 53, NameArabic = "النَّجۡمِ", NameEnglish = "An-Najm", NameBangla = "The Star", TotalAyahs = 62 },
            new Surah { Id = 54, SurahNumber = 54, NameArabic = "القَمَرِ", NameEnglish = "Al-Qamar", NameBangla = "The Moon", TotalAyahs = 55 },
            new Surah { Id = 55, SurahNumber = 55, NameArabic = "الرَّحۡمَٰن", NameEnglish = "Ar-Rahmaan", NameBangla = "The Beneficent", TotalAyahs = 78 },
            new Surah { Id = 56, SurahNumber = 56, NameArabic = "الوَاقِعَةِ", NameEnglish = "Al-Waaqia", NameBangla = "The Inevitable", TotalAyahs = 96 },
            new Surah { Id = 57, SurahNumber = 57, NameArabic = "الحَدِيدِ", NameEnglish = "Al-Hadid", NameBangla = "The Iron", TotalAyahs = 29 },
            new Surah { Id = 58, SurahNumber = 58, NameArabic = "المُجَادلَةِ", NameEnglish = "Al-Mujaadila", NameBangla = "The Pleading Woman", TotalAyahs = 22 },
            new Surah { Id = 59, SurahNumber = 59, NameArabic = "الحَشۡرِ", NameEnglish = "Al-Hashr", NameBangla = "The Exile", TotalAyahs = 24 },
            new Surah { Id = 60, SurahNumber = 60, NameArabic = "المُمۡتَحنَةِ", NameEnglish = "Al-Mumtahana", NameBangla = "She that is to be examined", TotalAyahs = 13 },
            new Surah { Id = 61, SurahNumber = 61, NameArabic = "الصَّفِّ", NameEnglish = "As-Saff", NameBangla = "The Ranks", TotalAyahs = 14 },
            new Surah { Id = 62, SurahNumber = 62, NameArabic = "الجُمُعَةِ", NameEnglish = "Al-Jumu'a", NameBangla = "Friday", TotalAyahs = 11 },
            new Surah { Id = 63, SurahNumber = 63, NameArabic = "المُنَافِقُونَ", NameEnglish = "Al-Munaafiqoon", NameBangla = "The Hypocrites", TotalAyahs = 11 },
            new Surah { Id = 64, SurahNumber = 64, NameArabic = "التَّغَابُنِ", NameEnglish = "At-Taghaabun", NameBangla = "Mutual Disillusion", TotalAyahs = 18 },
            new Surah { Id = 65, SurahNumber = 65, NameArabic = "الطَّلَاقِ", NameEnglish = "At-Talaaq", NameBangla = "Divorce", TotalAyahs = 12 },
            new Surah { Id = 66, SurahNumber = 66, NameArabic = "التَّحۡرِيمِ", NameEnglish = "At-Tahrim", NameBangla = "The Prohibition", TotalAyahs = 12 },
            new Surah { Id = 67, SurahNumber = 67, NameArabic = "المُلۡكِ", NameEnglish = "Al-Mulk", NameBangla = "The Sovereignty", TotalAyahs = 30 },
            new Surah { Id = 68, SurahNumber = 68, NameArabic = "القَلَمِ", NameEnglish = "Al-Qalam", NameBangla = "The Pen", TotalAyahs = 52 },
            new Surah { Id = 69, SurahNumber = 69, NameArabic = "الحَاقَّةِ", NameEnglish = "Al-Haaqqa", NameBangla = "The Reality", TotalAyahs = 52 },
            new Surah { Id = 70, SurahNumber = 70, NameArabic = "المَعَارِجِ", NameEnglish = "Al-Ma'aarij", NameBangla = "The Ascending Stairways", TotalAyahs = 44 },
            new Surah { Id = 71, SurahNumber = 71, NameArabic = "نُوحٍ", NameEnglish = "Nooh", NameBangla = "Noah", TotalAyahs = 28 },
            new Surah { Id = 72, SurahNumber = 72, NameArabic = "الجِنِّ", NameEnglish = "Al-Jinn", NameBangla = "The Jinn", TotalAyahs = 28 },
            new Surah { Id = 73, SurahNumber = 73, NameArabic = "المُزَّمِّلِ", NameEnglish = "Al-Muzzammil", NameBangla = "The Enshrouded One", TotalAyahs = 20 },
            new Surah { Id = 74, SurahNumber = 74, NameArabic = "المُدَّثِّرِ", NameEnglish = "Al-Muddaththir", NameBangla = "The Cloaked One", TotalAyahs = 56 },
            new Surah { Id = 75, SurahNumber = 75, NameArabic = "القِيَامَةِ", NameEnglish = "Al-Qiyaama", NameBangla = "The Resurrection", TotalAyahs = 40 },
            new Surah { Id = 76, SurahNumber = 76, NameArabic = "الإِنسَانِ", NameEnglish = "Al-Insaan", NameBangla = "Man", TotalAyahs = 31 },
            new Surah { Id = 77, SurahNumber = 77, NameArabic = "المُرۡسَلَاتِ", NameEnglish = "Al-Mursalaat", NameBangla = "The Emissaries", TotalAyahs = 50 },
            new Surah { Id = 78, SurahNumber = 78, NameArabic = "النَّبَإِ", NameEnglish = "An-Naba", NameBangla = "The Announcement", TotalAyahs = 40 },
            new Surah { Id = 79, SurahNumber = 79, NameArabic = "النَّازِعَاتِ", NameEnglish = "An-Naazi'aat", NameBangla = "Those who drag forth", TotalAyahs = 46 },
            new Surah { Id = 80, SurahNumber = 80, NameArabic = "عَبَسَ", NameEnglish = "Abasa", NameBangla = "He frowned", TotalAyahs = 42 },
            new Surah { Id = 81, SurahNumber = 81, NameArabic = "التَّكۡوِيرِ", NameEnglish = "At-Takwir", NameBangla = "The Overthrowing", TotalAyahs = 29 },
            new Surah { Id = 82, SurahNumber = 82, NameArabic = "الانفِطَارِ", NameEnglish = "Al-Infitaar", NameBangla = "The Cleaving", TotalAyahs = 19 },
            new Surah { Id = 83, SurahNumber = 83, NameArabic = "المُطَفِّفِينَ", NameEnglish = "Al-Mutaffifin", NameBangla = "Defrauding", TotalAyahs = 36 },
            new Surah { Id = 84, SurahNumber = 84, NameArabic = "الانشِقَاقِ", NameEnglish = "Al-Inshiqaaq", NameBangla = "The Splitting Open", TotalAyahs = 25 },
            new Surah { Id = 85, SurahNumber = 85, NameArabic = "البُرُوجِ", NameEnglish = "Al-Burooj", NameBangla = "The Constellations", TotalAyahs = 22 },
            new Surah { Id = 86, SurahNumber = 86, NameArabic = "الطَّارِقِ", NameEnglish = "At-Taariq", NameBangla = "The Morning Star", TotalAyahs = 17 },
            new Surah { Id = 87, SurahNumber = 87, NameArabic = "الأَعۡلَىٰ", NameEnglish = "Al-A'laa", NameBangla = "The Most High", TotalAyahs = 19 },
            new Surah { Id = 88, SurahNumber = 88, NameArabic = "الغَاشِيَةِ", NameEnglish = "Al-Ghaashiya", NameBangla = "The Overwhelming", TotalAyahs = 26 },
            new Surah { Id = 89, SurahNumber = 89, NameArabic = "الفَجۡرِ", NameEnglish = "Al-Fajr", NameBangla = "The Dawn", TotalAyahs = 30 },
            new Surah { Id = 90, SurahNumber = 90, NameArabic = "البَلَدِ", NameEnglish = "Al-Balad", NameBangla = "The City", TotalAyahs = 20 },
            new Surah { Id = 91, SurahNumber = 91, NameArabic = "الشَّمۡسِ", NameEnglish = "Ash-Shams", NameBangla = "The Sun", TotalAyahs = 15 },
            new Surah { Id = 92, SurahNumber = 92, NameArabic = "اللَّيۡلِ", NameEnglish = "Al-Lail", NameBangla = "The Night", TotalAyahs = 21 },
            new Surah { Id = 93, SurahNumber = 93, NameArabic = "الضُّحَىٰ", NameEnglish = "Ad-Dhuhaa", NameBangla = "The Morning Hours", TotalAyahs = 11 },
            new Surah { Id = 94, SurahNumber = 94, NameArabic = "الشَّرۡحِ", NameEnglish = "Ash-Sharh", NameBangla = "The Consolation", TotalAyahs = 8 },
            new Surah { Id = 95, SurahNumber = 95, NameArabic = "التِّينِ", NameEnglish = "At-Tin", NameBangla = "The Fig", TotalAyahs = 8 },
            new Surah { Id = 96, SurahNumber = 96, NameArabic = "العَلَقِ", NameEnglish = "Al-Alaq", NameBangla = "The Clot", TotalAyahs = 19 },
            new Surah { Id = 97, SurahNumber = 97, NameArabic = "القَدۡرِ", NameEnglish = "Al-Qadr", NameBangla = "The Power, Fate", TotalAyahs = 5 },
            new Surah { Id = 98, SurahNumber = 98, NameArabic = "البَيِّنَةِ", NameEnglish = "Al-Bayyina", NameBangla = "The Evidence", TotalAyahs = 8 },
            new Surah { Id = 99, SurahNumber = 99, NameArabic = "الزَّلۡزَلَةِ", NameEnglish = "Az-Zalzala", NameBangla = "The Earthquake", TotalAyahs = 8 },
            new Surah { Id = 100, SurahNumber = 100, NameArabic = "العَادِيَاتِ", NameEnglish = "Al-Aadiyaat", NameBangla = "The Chargers", TotalAyahs = 11 },
            new Surah { Id = 101, SurahNumber = 101, NameArabic = "القَارِعَةِ", NameEnglish = "Al-Qaari'a", NameBangla = "The Calamity", TotalAyahs = 11 },
            new Surah { Id = 102, SurahNumber = 102, NameArabic = "التَّكَاثُرِ", NameEnglish = "At-Takaathur", NameBangla = "Competition", TotalAyahs = 8 },
            new Surah { Id = 103, SurahNumber = 103, NameArabic = "العَصۡرِ", NameEnglish = "Al-Asr", NameBangla = "The Declining Day", TotalAyahs = 3 },
            new Surah { Id = 104, SurahNumber = 104, NameArabic = "الهُمَزَةِ", NameEnglish = "Al-Humaza", NameBangla = "The Traducer", TotalAyahs = 9 },
            new Surah { Id = 105, SurahNumber = 105, NameArabic = "الفِيلِ", NameEnglish = "Al-Fil", NameBangla = "The Elephant", TotalAyahs = 5 },
            new Surah { Id = 106, SurahNumber = 106, NameArabic = "قُرَيۡشٍ", NameEnglish = "Quraish", NameBangla = "Quraysh", TotalAyahs = 4 },
            new Surah { Id = 107, SurahNumber = 107, NameArabic = "المَاعُونِ", NameEnglish = "Al-Maa'un", NameBangla = "Almsgiving", TotalAyahs = 7 },
            new Surah { Id = 108, SurahNumber = 108, NameArabic = "الكَوۡثَرِ", NameEnglish = "Al-Kawthar", NameBangla = "Abundance", TotalAyahs = 3 },
            new Surah { Id = 109, SurahNumber = 109, NameArabic = "الكَافِرُونَ", NameEnglish = "Al-Kaafiroon", NameBangla = "The Disbelievers", TotalAyahs = 6 },
            new Surah { Id = 110, SurahNumber = 110, NameArabic = "النَّصۡرِ", NameEnglish = "An-Nasr", NameBangla = "Divine Support", TotalAyahs = 3 },
            new Surah { Id = 111, SurahNumber = 111, NameArabic = "المَسَدِ", NameEnglish = "Al-Masad", NameBangla = "The Palm Fibre", TotalAyahs = 5 },
            new Surah { Id = 112, SurahNumber = 112, NameArabic = "الإِخۡلَاصِ", NameEnglish = "Al-Ikhlaas", NameBangla = "Sincerity", TotalAyahs = 4 },
            new Surah { Id = 113, SurahNumber = 113, NameArabic = "الفَلَقِ", NameEnglish = "Al-Falaq", NameBangla = "The Dawn", TotalAyahs = 5 },
            new Surah { Id = 114, SurahNumber = 114, NameArabic = "النَّاسِ", NameEnglish = "An-Naas", NameBangla = "Mankind", TotalAyahs = 6 }
        );
    }
}
