// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Persistence;

#nullable disable

namespace backend.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525175519_Phase3_PronunciationTables")]
    partial class Phase3_PronunciationTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Domain.Entities.AudioRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StreamingSessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StreamingSessionId");

                    b.ToTable("AudioRecords", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.Ayah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("AyahNumber")
                        .HasColumnType("integer");

                    b.Property<string>("BanglaTranslation")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("EnglishTranslation")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("NormalizedArabicText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("SurahId")
                        .HasColumnType("integer");

                    b.Property<string>("Transliteration")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("SurahId", "AyahNumber")
                        .IsUnique();

                    b.ToTable("Ayahs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArabicText = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
                            AyahNumber = 1,
                            BanglaTranslation = "পরম করুণাময় অতি দয়ালু আল্লাহর নামে।",
                            EnglishTranslation = "In the name of Allah, the Most Gracious, the Most Merciful.",
                            NormalizedArabicText = "بسم الله الرحمن الرحيم",
                            SurahId = 1,
                            Transliteration = "Bismillahi r-rahmani r-raheem"
                        },
                        new
                        {
                            Id = 2,
                            ArabicText = "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
                            AyahNumber = 2,
                            BanglaTranslation = "সমস্ত প্রশংসা আল্লাহর জন্য, যিনি সমগ্র জগতের প্রতিপালক।",
                            EnglishTranslation = "All praise is due to Allah, Lord of all the worlds.",
                            NormalizedArabicText = "الحمد لله رب العالمين",
                            SurahId = 1,
                            Transliteration = "Alhamdu lillahi rabbi l-'alamin"
                        },
                        new
                        {
                            Id = 3,
                            ArabicText = "الرَّحْمَٰنِ الرَّحِيمِ",
                            AyahNumber = 3,
                            BanglaTranslation = "পরম করুণাময়, অতি দয়ালু।",
                            EnglishTranslation = "The Most Gracious, the Most Merciful.",
                            NormalizedArabicText = "الرحمن الرحيم",
                            SurahId = 1,
                            Transliteration = "Ar-rahmani r-raheem"
                        },
                        new
                        {
                            Id = 4,
                            ArabicText = "مَالِكِ يَوْمِ الدِّينِ",
                            AyahNumber = 4,
                            BanglaTranslation = "বিচার দিনের মালিক।",
                            EnglishTranslation = "Master of the Day of Judgment.",
                            NormalizedArabicText = "مالك يوم الدين",
                            SurahId = 1,
                            Transliteration = "Maliki yawmi d-deen"
                        },
                        new
                        {
                            Id = 5,
                            ArabicText = "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ",
                            AyahNumber = 5,
                            BanglaTranslation = "আমরা কেবল তোমারই ইবাদত করি এবং কেবল তোমারই সাহায্য চাই।",
                            EnglishTranslation = "You alone we worship, and You alone we ask for help.",
                            NormalizedArabicText = "اياك نعبد واياك نستعين",
                            SurahId = 1,
                            Transliteration = "Iyyaka na'budu wa-iyyaka nasta'een"
                        },
                        new
                        {
                            Id = 6,
                            ArabicText = "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ",
                            AyahNumber = 6,
                            BanglaTranslation = "আমাদের সরল পথ দেখাও।",
                            EnglishTranslation = "Guide us to the straight path.",
                            NormalizedArabicText = "اهدنا الصراط المستقيم",
                            SurahId = 1,
                            Transliteration = "Ihdina s-sirata l-mustaqeem"
                        },
                        new
                        {
                            Id = 7,
                            ArabicText = "صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
                            AyahNumber = 7,
                            BanglaTranslation = "তাদের পথ, যাদের তুমি নেয়ামত দিয়েছ; তাদের পথ নয় যাদের উপর তোমার ক্রোধ আছে এবং যারা পথভ্রষ্ট।",
                            EnglishTranslation = "The path of those upon whom You have bestowed favor, not of those who have evoked Your anger or of those who are astray.",
                            NormalizedArabicText = "صراط الذين انعمت عليهم غير المغضوب عليهم ولا الضالين",
                            SurahId = 1,
                            Transliteration = "Sirata l-ladhina an'amta 'alayhim ghayri l-maghdubi 'alayhim wa-la d-dalleen"
                        });
                });

            modelBuilder.Entity("backend.Domain.Entities.PhonemeResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AccuracyScore")
                        .HasColumnType("double precision");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsWeak")
                        .HasColumnType("boolean");

                    b.Property<string>("Phoneme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("WordPronunciationResultId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WordPronunciationResultId");

                    b.ToTable("PhonemeResults", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.PronunciationAssessmentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AccuracyScore")
                        .HasColumnType("double precision");

                    b.Property<int>("AyahId")
                        .HasColumnType("integer");

                    b.Property<double>("CompletenessScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FluencyScore")
                        .HasColumnType("double precision");

                    b.Property<double>("PronunciationScore")
                        .HasColumnType("double precision");

                    b.Property<string>("RecognizedText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("StreamingSessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AyahId");

                    b.HasIndex("StreamingSessionId");

                    b.ToTable("PronunciationAssessmentResults", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.RecitationSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("AyahId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedRecognizedText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("RecognizedText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AyahId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("UserId");

                    b.ToTable("RecitationSessions", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.SpeechRecognitionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RecognizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecognizedText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StreamingSessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StreamingSessionId");

                    b.ToTable("SpeechRecognitionResults", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.StreamingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("StreamingSessions", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.Surah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameBangla")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SurahNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAyahs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SurahNumber")
                        .IsUnique();

                    b.ToTable("Surahs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameArabic = "الفاتحة",
                            NameBangla = "সূচনা",
                            NameEnglish = "The Opening",
                            SurahNumber = 1,
                            TotalAyahs = 7
                        });
                });

            modelBuilder.Entity("backend.Domain.Entities.WebSocketConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DisconnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("UserId");

                    b.ToTable("WebSocketConnections", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.WordPronunciationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AccuracyScore")
                        .HasColumnType("double precision");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<long>("Offset")
                        .HasColumnType("bigint");

                    b.Property<int>("PronunciationAssessmentResultId")
                        .HasColumnType("integer");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("PronunciationAssessmentResultId");

                    b.ToTable("WordPronunciationResults", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.Ayah", b =>
                {
                    b.HasOne("backend.Domain.Entities.Surah", "Surah")
                        .WithMany()
                        .HasForeignKey("SurahId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Surah");
                });

            modelBuilder.Entity("backend.Domain.Entities.PhonemeResult", b =>
                {
                    b.HasOne("backend.Domain.Entities.WordPronunciationResult", "Word")
                        .WithMany("Phonemes")
                        .HasForeignKey("WordPronunciationResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("backend.Domain.Entities.PronunciationAssessmentResult", b =>
                {
                    b.HasOne("backend.Domain.Entities.Ayah", "Ayah")
                        .WithMany()
                        .HasForeignKey("AyahId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.StreamingSession", "StreamingSession")
                        .WithMany()
                        .HasForeignKey("StreamingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ayah");

                    b.Navigation("StreamingSession");
                });

            modelBuilder.Entity("backend.Domain.Entities.RecitationSession", b =>
                {
                    b.HasOne("backend.Domain.Entities.Ayah", "Ayah")
                        .WithMany()
                        .HasForeignKey("AyahId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ayah");
                });

            modelBuilder.Entity("backend.Domain.Entities.SpeechRecognitionResult", b =>
                {
                    b.HasOne("backend.Domain.Entities.StreamingSession", "StreamingSession")
                        .WithMany()
                        .HasForeignKey("StreamingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamingSession");
                });

            modelBuilder.Entity("backend.Domain.Entities.WordPronunciationResult", b =>
                {
                    b.HasOne("backend.Domain.Entities.PronunciationAssessmentResult", "Assessment")
                        .WithMany("Words")
                        .HasForeignKey("PronunciationAssessmentResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("backend.Domain.Entities.PronunciationAssessmentResult", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("backend.Domain.Entities.WordPronunciationResult", b =>
                {
                    b.Navigation("Phonemes");
                });
#pragma warning restore 612, 618
        }
    }
}
