// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Persistence;

#nullable disable

namespace backend.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526093949_AddArabicLetters")]
    partial class AddArabicLetters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Domain.Entities.ArabicLetter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExampleWord")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExampleWordArabic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MakhrajDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("MakhrajType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameBangla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Sifaat")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Transliteration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Order")
                        .IsUnique();

                    b.ToTable("ArabicLetters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExampleWord = "One (Ahad)",
                            ExampleWordArabic = "أَحَد",
                            Letter = "ا",
                            MakhrajDescription = "Deepest part of the throat (Hamza); Alif itself is a vowel carrier",
                            MakhrajType = "Throat",
                            NameArabic = "أَلِف",
                            NameBangla = "আলিফ",
                            NameEnglish = "Alif",
                            Order = 1,
                            Sifaat = "Jahr,Rakhawa,Istifal,Infitah,Idhlag",
                            Transliteration = "ā / ʾ"
                        },
                        new
                        {
                            Id = 2,
                            ExampleWord = "House (Bayt)",
                            ExampleWordArabic = "بَيْت",
                            Letter = "ب",
                            MakhrajDescription = "Both lips pressed together (bilabial stop)",
                            MakhrajType = "Lips",
                            NameArabic = "بَاء",
                            NameBangla = "বা",
                            NameEnglish = "Ba",
                            Order = 2,
                            Sifaat = "Jahr,Shiddah,Istifal,Infitah,Idhlag,Qalqalah",
                            Transliteration = "b"
                        },
                        new
                        {
                            Id = 3,
                            ExampleWord = "Dates (Tamr)",
                            ExampleWordArabic = "تَمْر",
                            Letter = "ت",
                            MakhrajDescription = "Tip of tongue touches the upper front teeth",
                            MakhrajType = "TongueTipDental",
                            NameArabic = "تَاء",
                            NameBangla = "তা",
                            NameEnglish = "Ta",
                            Order = 3,
                            Sifaat = "Hams,Shiddah,Istifal,Infitah,Idhlag",
                            Transliteration = "t"
                        },
                        new
                        {
                            Id = 4,
                            ExampleWord = "Garment (Thawb)",
                            ExampleWordArabic = "ثَوْب",
                            Letter = "ث",
                            MakhrajDescription = "Tip of tongue lightly between the upper and lower teeth",
                            MakhrajType = "TongueTipInterdental",
                            NameArabic = "ثَاء",
                            NameBangla = "ছা",
                            NameEnglish = "Tha",
                            Order = 4,
                            Sifaat = "Hams,Rakhawa,Istifal,Infitah,Idhlag",
                            Transliteration = "th"
                        },
                        new
                        {
                            Id = 5,
                            ExampleWord = "Mountain (Jabal)",
                            ExampleWordArabic = "جَبَل",
                            Letter = "ج",
                            MakhrajDescription = "Middle of the tongue meets the hard palate",
                            MakhrajType = "TongueFront",
                            NameArabic = "جِيم",
                            NameBangla = "জিম",
                            NameEnglish = "Jim",
                            Order = 5,
                            Sifaat = "Jahr,Shiddah,Istifal,Infitah,Idhlag,Qalqalah",
                            Transliteration = "j"
                        },
                        new
                        {
                            Id = 6,
                            ExampleWord = "Truth (Haqq)",
                            ExampleWordArabic = "حَق",
                            Letter = "ح",
                            MakhrajDescription = "Middle of the throat — a breathy, voiceless pharyngeal fricative",
                            MakhrajType = "UpperThroat",
                            NameArabic = "حَاء",
                            NameBangla = "হা",
                            NameEnglish = "Ha",
                            Order = 6,
                            Sifaat = "Hams,Rakhawa,Istifal,Infitah,Idhlag",
                            Transliteration = "ḥ"
                        },
                        new
                        {
                            Id = 7,
                            ExampleWord = "Goodness (Khayr)",
                            ExampleWordArabic = "خَيْر",
                            Letter = "خ",
                            MakhrajDescription = "Upper throat (closest to mouth) — velar fricative, like a raspy 'kh'",
                            MakhrajType = "UpperThroat",
                            NameArabic = "خَاء",
                            NameBangla = "খা",
                            NameEnglish = "Kha",
                            Order = 7,
                            Sifaat = "Hams,Rakhawa,Isti'la,Infitah,Idhlag",
                            Transliteration = "kh"
                        },
                        new
                        {
                            Id = 8,
                            ExampleWord = "Religion (Deen)",
                            ExampleWordArabic = "دِين",
                            Letter = "د",
                            MakhrajDescription = "Tip and sides of tongue against the upper front teeth",
                            MakhrajType = "TongueTipDental",
                            NameArabic = "دَال",
                            NameBangla = "দাল",
                            NameEnglish = "Dal",
                            Order = 8,
                            Sifaat = "Jahr,Shiddah,Istifal,Infitah,Idhlag,Qalqalah",
                            Transliteration = "d"
                        },
                        new
                        {
                            Id = 9,
                            ExampleWord = "Remembrance (Dhikr)",
                            ExampleWordArabic = "ذِكْر",
                            Letter = "ذ",
                            MakhrajDescription = "Tip of tongue lightly between the upper and lower teeth (voiced)",
                            MakhrajType = "TongueTipInterdental",
                            NameArabic = "ذَال",
                            NameBangla = "যাল",
                            NameEnglish = "Dhal",
                            Order = 9,
                            Sifaat = "Jahr,Rakhawa,Istifal,Infitah,Idhlag",
                            Transliteration = "dh"
                        },
                        new
                        {
                            Id = 10,
                            ExampleWord = "Mercy (Rahma)",
                            ExampleWordArabic = "رَحْمَة",
                            Letter = "ر",
                            MakhrajDescription = "Tip of tongue near the upper gum ridge — a trilled or tapped 'r'",
                            MakhrajType = "TongueTipTrilled",
                            NameArabic = "رَاء",
                            NameBangla = "রা",
                            NameEnglish = "Ra",
                            Order = 10,
                            Sifaat = "Jahr,Tawassut,Istifal,Infitah,Idhlag,Takrir",
                            Transliteration = "r"
                        },
                        new
                        {
                            Id = 11,
                            ExampleWord = "Oil (Zayt)",
                            ExampleWordArabic = "زَيْت",
                            Letter = "ز",
                            MakhrajDescription = "Tip of tongue near the lower front teeth — voiced sibilant",
                            MakhrajType = "TongueTipSibilant",
                            NameArabic = "زَاي",
                            NameBangla = "যায়",
                            NameEnglish = "Zay",
                            Order = 11,
                            Sifaat = "Jahr,Rakhawa,Istifal,Infitah,Idhlag,Safeer",
                            Transliteration = "z"
                        },
                        new
                        {
                            Id = 12,
                            ExampleWord = "Peace (Salaam)",
                            ExampleWordArabic = "سَلَام",
                            Letter = "س",
                            MakhrajDescription = "Tip of tongue near the lower front teeth — voiceless sibilant",
                            MakhrajType = "TongueTipSibilant",
                            NameArabic = "سِين",
                            NameBangla = "সিন",
                            NameEnglish = "Sin",
                            Order = 12,
                            Sifaat = "Hams,Rakhawa,Istifal,Infitah,Idhlag,Safeer",
                            Transliteration = "s"
                        },
                        new
                        {
                            Id = 13,
                            ExampleWord = "Sun (Shams)",
                            ExampleWordArabic = "شَمْس",
                            Letter = "ش",
                            MakhrajDescription = "Middle of the tongue spread toward the hard palate — 'sh' sound",
                            MakhrajType = "TongueFront",
                            NameArabic = "شِين",
                            NameBangla = "শিন",
                            NameEnglish = "Shin",
                            Order = 13,
                            Sifaat = "Hams,Rakhawa,Istifal,Infitah,Idhlag,Tafasshi",
                            Transliteration = "sh"
                        },
                        new
                        {
                            Id = 14,
                            ExampleWord = "Patience (Sabr)",
                            ExampleWordArabic = "صَبْر",
                            Letter = "ص",
                            MakhrajDescription = "Tip of tongue near front teeth — heavy emphatic 'S' with tongue raised",
                            MakhrajType = "TongueTipSibilant",
                            NameArabic = "صَاد",
                            NameBangla = "সাদ",
                            NameEnglish = "Sad",
                            Order = 14,
                            Sifaat = "Hams,Rakhawa,Isti'la,Itbaq,Idhlag,Safeer",
                            Transliteration = "ṣ"
                        },
                        new
                        {
                            Id = 15,
                            ExampleWord = "Light (Daw')",
                            ExampleWordArabic = "ضَوْء",
                            Letter = "ض",
                            MakhrajDescription = "One or both sides of the tongue against the upper back molars",
                            MakhrajType = "TongueSide",
                            NameArabic = "ضَاد",
                            NameBangla = "দোয়াদ",
                            NameEnglish = "Dad",
                            Order = 15,
                            Sifaat = "Jahr,Rakhawa,Isti'la,Itbaq,Idhlag",
                            Transliteration = "ḍ"
                        },
                        new
                        {
                            Id = 16,
                            ExampleWord = "Road (Tariq)",
                            ExampleWordArabic = "طَرِيق",
                            Letter = "ط",
                            MakhrajDescription = "Tip of tongue touches upper front teeth — emphatic heavy 'T'",
                            MakhrajType = "TongueTipDental",
                            NameArabic = "طَاء",
                            NameBangla = "তোয়া",
                            NameEnglish = "Taa",
                            Order = 16,
                            Sifaat = "Jahr,Shiddah,Isti'la,Itbaq,Idhlag,Qalqalah",
                            Transliteration = "ṭ"
                        },
                        new
                        {
                            Id = 17,
                            ExampleWord = "Oppression (Dhulm)",
                            ExampleWordArabic = "ظُلْم",
                            Letter = "ظ",
                            MakhrajDescription = "Tip of tongue between teeth — heavy emphatic interdental",
                            MakhrajType = "TongueTipInterdental",
                            NameArabic = "ظَاء",
                            NameBangla = "যোয়া",
                            NameEnglish = "Dhaa",
                            Order = 17,
                            Sifaat = "Jahr,Rakhawa,Isti'la,Itbaq,Idhlag",
                            Transliteration = "ẓ"
                        },
                        new
                        {
                            Id = 18,
                            ExampleWord = "Knowledge (Ilm)",
                            ExampleWordArabic = "عِلْم",
                            Letter = "ع",
                            MakhrajDescription = "Middle of the throat — voiced pharyngeal fricative, a unique Arabic sound",
                            MakhrajType = "MidThroat",
                            NameArabic = "عَيْن",
                            NameBangla = "আইন",
                            NameEnglish = "Ayn",
                            Order = 18,
                            Sifaat = "Jahr,Tawassut,Istifal,Infitah,Idhlag",
                            Transliteration = "ʿ"
                        },
                        new
                        {
                            Id = 19,
                            ExampleWord = "Unseen (Ghayb)",
                            ExampleWordArabic = "غَيْب",
                            Letter = "غ",
                            MakhrajDescription = "Upper throat — voiced velar fricative, a gargling 'gh' sound",
                            MakhrajType = "MidThroat",
                            NameArabic = "غَيْن",
                            NameBangla = "গাইন",
                            NameEnglish = "Ghayn",
                            Order = 19,
                            Sifaat = "Jahr,Rakhawa,Isti'la,Infitah,Idhlag",
                            Transliteration = "gh"
                        },
                        new
                        {
                            Id = 20,
                            ExampleWord = "Dawn (Fajr)",
                            ExampleWordArabic = "فَجْر",
                            Letter = "ف",
                            MakhrajDescription = "Inner edge of the lower lip touches the tips of the upper front teeth",
                            MakhrajType = "Labiodental",
                            NameArabic = "فَاء",
                            NameBangla = "ফা",
                            NameEnglish = "Fa",
                            Order = 20,
                            Sifaat = "Hams,Rakhawa,Istifal,Infitah,Idhlag",
                            Transliteration = "f"
                        },
                        new
                        {
                            Id = 21,
                            ExampleWord = "Quran (Quran)",
                            ExampleWordArabic = "قُرْآن",
                            Letter = "ق",
                            MakhrajDescription = "Back of tongue touches the soft palate (uvular stop)",
                            MakhrajType = "TongueBack",
                            NameArabic = "قَاف",
                            NameBangla = "কাফ",
                            NameEnglish = "Qaf",
                            Order = 21,
                            Sifaat = "Jahr,Shiddah,Isti'la,Infitah,Ismat,Qalqalah",
                            Transliteration = "q"
                        },
                        new
                        {
                            Id = 22,
                            ExampleWord = "Book (Kitab)",
                            ExampleWordArabic = "كِتَاب",
                            Letter = "ك",
                            MakhrajDescription = "Back of tongue touches the hard palate — slightly forward of Qaf",
                            MakhrajType = "TongueBack",
                            NameArabic = "كَاف",
                            NameBangla = "কাফ",
                            NameEnglish = "Kaf",
                            Order = 22,
                            Sifaat = "Hams,Shiddah,Istifal,Infitah,Ismat",
                            Transliteration = "k"
                        },
                        new
                        {
                            Id = 23,
                            ExampleWord = "Night (Layl)",
                            ExampleWordArabic = "لَيْل",
                            Letter = "ل",
                            MakhrajDescription = "Tip and sides of tongue along the upper gum ridge — lateral sound",
                            MakhrajType = "TongueSide",
                            NameArabic = "لَام",
                            NameBangla = "লাম",
                            NameEnglish = "Lam",
                            Order = 23,
                            Sifaat = "Jahr,Tawassut,Istifal,Infitah,Idhlag,Inhiraf",
                            Transliteration = "l"
                        },
                        new
                        {
                            Id = 24,
                            ExampleWord = "Water (Maa')",
                            ExampleWordArabic = "مَاء",
                            Letter = "م",
                            MakhrajDescription = "Both lips closed together — bilabial nasal",
                            MakhrajType = "Lips",
                            NameArabic = "مِيم",
                            NameBangla = "মিম",
                            NameEnglish = "Mim",
                            Order = 24,
                            Sifaat = "Jahr,Tawassut,Istifal,Infitah,Idhlag",
                            Transliteration = "m"
                        },
                        new
                        {
                            Id = 25,
                            ExampleWord = "Light (Nur)",
                            ExampleWordArabic = "نُور",
                            Letter = "ن",
                            MakhrajDescription = "Tip of tongue near the upper gum ridge — alveolar nasal",
                            MakhrajType = "TongueTipAlveolar",
                            NameArabic = "نُون",
                            NameBangla = "নুন",
                            NameEnglish = "Nun",
                            Order = 25,
                            Sifaat = "Jahr,Tawassut,Istifal,Infitah,Idhlag,Ghunnah",
                            Transliteration = "n"
                        },
                        new
                        {
                            Id = 26,
                            ExampleWord = "Child (Walad)",
                            ExampleWordArabic = "وَلَد",
                            Letter = "و",
                            MakhrajDescription = "Both lips rounded and slightly apart — labio-velar semi-vowel",
                            MakhrajType = "Lips",
                            NameArabic = "وَاو",
                            NameBangla = "ওয়াও",
                            NameEnglish = "Waw",
                            Order = 26,
                            Sifaat = "Jahr,Rakhawa,Istifal,Infitah,Idhlag,Lin",
                            Transliteration = "w / ū"
                        },
                        new
                        {
                            Id = 27,
                            ExampleWord = "Guidance (Huda)",
                            ExampleWordArabic = "هُدَى",
                            Letter = "ه",
                            MakhrajDescription = "Deepest part of the throat — a soft, breathy voiceless glottal fricative",
                            MakhrajType = "Throat",
                            NameArabic = "هَاء",
                            NameBangla = "হা",
                            NameEnglish = "Ha",
                            Order = 27,
                            Sifaat = "Hams,Rakhawa,Istifal,Infitah,Idhlag",
                            Transliteration = "h"
                        },
                        new
                        {
                            Id = 28,
                            ExampleWord = "Day (Yawm)",
                            ExampleWordArabic = "يَوْم",
                            Letter = "ي",
                            MakhrajDescription = "Middle of the tongue rises toward the hard palate — palatal semi-vowel",
                            MakhrajType = "TongueFront",
                            NameArabic = "يَاء",
                            NameBangla = "ইয়া",
                            NameEnglish = "Ya",
                            Order = 28,
                            Sifaat = "Jahr,Rakhawa,Istifal,Infitah,Idhlag,Lin",
                            Transliteration = "y / ī"
                        });
                });

            modelBuilder.Entity("backend.Domain.Entities.AudioRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StreamingSessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StreamingSessionId");

                    b.ToTable("AudioRecords", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.Ayah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("AyahNumber")
                        .HasColumnType("integer");

                    b.Property<string>("BanglaTranslation")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("EnglishTranslation")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("NormalizedArabicText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("SurahId")
                        .HasColumnType("integer");

                    b.Property<string>("Transliteration")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("SurahId", "AyahNumber")
                        .IsUnique();

                    b.ToTable("Ayahs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArabicText = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
                            AyahNumber = 1,
                            BanglaTranslation = "পরম করুণাময় অতি দয়ালু আল্লাহর নামে।",
                            EnglishTranslation = "In the name of Allah, the Most Gracious, the Most Merciful.",
                            NormalizedArabicText = "بسم الله الرحمن الرحيم",
                            SurahId = 1,
                            Transliteration = "Bismillahi r-rahmani r-raheem"
                        },
                        new
                        {
                            Id = 2,
                            ArabicText = "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
                            AyahNumber = 2,
                            BanglaTranslation = "সমস্ত প্রশংসা আল্লাহর জন্য, যিনি সমগ্র জগতের প্রতিপালক।",
                            EnglishTranslation = "All praise is due to Allah, Lord of all the worlds.",
                            NormalizedArabicText = "الحمد لله رب العالمين",
                            SurahId = 1,
                            Transliteration = "Alhamdu lillahi rabbi l-'alamin"
                        },
                        new
                        {
                            Id = 3,
                            ArabicText = "الرَّحْمَٰنِ الرَّحِيمِ",
                            AyahNumber = 3,
                            BanglaTranslation = "পরম করুণাময়, অতি দয়ালু।",
                            EnglishTranslation = "The Most Gracious, the Most Merciful.",
                            NormalizedArabicText = "الرحمن الرحيم",
                            SurahId = 1,
                            Transliteration = "Ar-rahmani r-raheem"
                        },
                        new
                        {
                            Id = 4,
                            ArabicText = "مَالِكِ يَوْمِ الدِّينِ",
                            AyahNumber = 4,
                            BanglaTranslation = "বিচার দিনের মালিক।",
                            EnglishTranslation = "Master of the Day of Judgment.",
                            NormalizedArabicText = "مالك يوم الدين",
                            SurahId = 1,
                            Transliteration = "Maliki yawmi d-deen"
                        },
                        new
                        {
                            Id = 5,
                            ArabicText = "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ",
                            AyahNumber = 5,
                            BanglaTranslation = "আমরা কেবল তোমারই ইবাদত করি এবং কেবল তোমারই সাহায্য চাই।",
                            EnglishTranslation = "You alone we worship, and You alone we ask for help.",
                            NormalizedArabicText = "اياك نعبد واياك نستعين",
                            SurahId = 1,
                            Transliteration = "Iyyaka na'budu wa-iyyaka nasta'een"
                        },
                        new
                        {
                            Id = 6,
                            ArabicText = "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ",
                            AyahNumber = 6,
                            BanglaTranslation = "আমাদের সরল পথ দেখাও।",
                            EnglishTranslation = "Guide us to the straight path.",
                            NormalizedArabicText = "اهدنا الصراط المستقيم",
                            SurahId = 1,
                            Transliteration = "Ihdina s-sirata l-mustaqeem"
                        },
                        new
                        {
                            Id = 7,
                            ArabicText = "صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
                            AyahNumber = 7,
                            BanglaTranslation = "তাদের পথ, যাদের তুমি নেয়ামত দিয়েছ; তাদের পথ নয় যাদের উপর তোমার ক্রোধ আছে এবং যারা পথভ্রষ্ট।",
                            EnglishTranslation = "The path of those upon whom You have bestowed favor, not of those who have evoked Your anger or of those who are astray.",
                            NormalizedArabicText = "صراط الذين انعمت عليهم غير المغضوب عليهم ولا الضالين",
                            SurahId = 1,
                            Transliteration = "Sirata l-ladhina an'amta 'alayhim ghayri l-maghdubi 'alayhim wa-la d-dalleen"
                        });
                });

            modelBuilder.Entity("backend.Domain.Entities.PhonemeResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AccuracyScore")
                        .HasColumnType("double precision");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsWeak")
                        .HasColumnType("boolean");

                    b.Property<string>("Phoneme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("WordPronunciationResultId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WordPronunciationResultId");

                    b.ToTable("PhonemeResults", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.PronunciationAssessmentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AccuracyScore")
                        .HasColumnType("double precision");

                    b.Property<int>("AyahId")
                        .HasColumnType("integer");

                    b.Property<double>("CompletenessScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FluencyScore")
                        .HasColumnType("double precision");

                    b.Property<double>("PronunciationScore")
                        .HasColumnType("double precision");

                    b.Property<string>("RecognizedText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("StreamingSessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AyahId");

                    b.HasIndex("StreamingSessionId");

                    b.ToTable("PronunciationAssessmentResults", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.RecitationSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("AyahId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedRecognizedText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("RecognizedText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AyahId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("UserId");

                    b.ToTable("RecitationSessions", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.SpeechRecognitionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RecognizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecognizedText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StreamingSessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StreamingSessionId");

                    b.ToTable("SpeechRecognitionResults", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.StreamingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("StreamingSessions", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.Surah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameBangla")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SurahNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAyahs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SurahNumber")
                        .IsUnique();

                    b.ToTable("Surahs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameArabic = "الفاتحة",
                            NameBangla = "সূচনা",
                            NameEnglish = "The Opening",
                            SurahNumber = 1,
                            TotalAyahs = 7
                        });
                });

            modelBuilder.Entity("backend.Domain.Entities.TajweedRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TajweedRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArabicName = "مد",
                            Description = "Elongation of vowel letters ا و ي for a minimum of 2 harakats.",
                            RuleType = "Madd"
                        },
                        new
                        {
                            Id = 2,
                            ArabicName = "غنة",
                            Description = "Nasalization of ن or م with shaddah, held for 2 harakats.",
                            RuleType = "Ghunnah"
                        },
                        new
                        {
                            Id = 3,
                            ArabicName = "قلقلة",
                            Description = "Echoing bounce on ق ط ب ج د when carrying sukoon or at word end.",
                            RuleType = "Qalqalah"
                        },
                        new
                        {
                            Id = 4,
                            ArabicName = "إخفاء",
                            Description = "Partial concealment of noon sakinah/tanween before 15 letters.",
                            RuleType = "Ikhfa"
                        },
                        new
                        {
                            Id = 5,
                            ArabicName = "إدغام",
                            Description = "Merging of noon sakinah/tanween into the following يرملون letter.",
                            RuleType = "Idgham"
                        });
                });

            modelBuilder.Entity("backend.Domain.Entities.WebSocketConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DisconnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("UserId");

                    b.ToTable("WebSocketConnections", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.WordPronunciationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AccuracyScore")
                        .HasColumnType("double precision");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<long>("Offset")
                        .HasColumnType("bigint");

                    b.Property<int>("PronunciationAssessmentResultId")
                        .HasColumnType("integer");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("PronunciationAssessmentResultId");

                    b.ToTable("WordPronunciationResults", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.Ayah", b =>
                {
                    b.HasOne("backend.Domain.Entities.Surah", "Surah")
                        .WithMany()
                        .HasForeignKey("SurahId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Surah");
                });

            modelBuilder.Entity("backend.Domain.Entities.PhonemeResult", b =>
                {
                    b.HasOne("backend.Domain.Entities.WordPronunciationResult", "Word")
                        .WithMany("Phonemes")
                        .HasForeignKey("WordPronunciationResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("backend.Domain.Entities.PronunciationAssessmentResult", b =>
                {
                    b.HasOne("backend.Domain.Entities.Ayah", "Ayah")
                        .WithMany()
                        .HasForeignKey("AyahId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.StreamingSession", "StreamingSession")
                        .WithMany()
                        .HasForeignKey("StreamingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ayah");

                    b.Navigation("StreamingSession");
                });

            modelBuilder.Entity("backend.Domain.Entities.RecitationSession", b =>
                {
                    b.HasOne("backend.Domain.Entities.Ayah", "Ayah")
                        .WithMany()
                        .HasForeignKey("AyahId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ayah");
                });

            modelBuilder.Entity("backend.Domain.Entities.SpeechRecognitionResult", b =>
                {
                    b.HasOne("backend.Domain.Entities.StreamingSession", "StreamingSession")
                        .WithMany()
                        .HasForeignKey("StreamingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamingSession");
                });

            modelBuilder.Entity("backend.Domain.Entities.WordPronunciationResult", b =>
                {
                    b.HasOne("backend.Domain.Entities.PronunciationAssessmentResult", "Assessment")
                        .WithMany("Words")
                        .HasForeignKey("PronunciationAssessmentResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("backend.Domain.Entities.PronunciationAssessmentResult", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("backend.Domain.Entities.WordPronunciationResult", b =>
                {
                    b.Navigation("Phonemes");
                });
#pragma warning restore 612, 618
        }
    }
}
